Replace Airflow quickstart with tutorial in marquez/examples
OpenLineage/docs pull request #185
Opened 2023-06-16 21:04 UTC by merobi-hub

We need an easy-to-configure and functional Airflow quickstart, but airflow.md in docs/guides is not working currently and requires complex configuration across multiple services.

This: 

- retitles airflow.md to reflect its focus on the proxy to give us a proxy guide
- updates and adds the Airflow tutorial in marquez/examples to serve as a lighter-weight, functional Airflow quickstart.

2023-06-28 17:25 UTC, JDarDagran approved these changes

2023-06-28 20:47 UTC, merobi-hub commented on docs/guides/new-quickstart.md
> +## Step 5: Troubleshoot a Failing DAG with Marquez
Thanks for noticing this @JDarDagran

2023-06-29 18:50 UTC, merobi-hub commented
Thanks @kentdanas for all the improvements. Incorporating them into a single forthcoming commit.

2023-07-07 12:16 UTC, wslulciuc requested changes
Thanks for improving the docs, @merobi-hub. I have some suggestion to simplify the setup steps:

1. Use published Marquez image
2. Use published OpenLineage proxy image
3. Define a combined docker compose file that sets up both services; users would no longer have to clone repos to get started or run any scripts.

2023-07-07 13:02 UTC, merobi-hub commented
Thanks @wslulciuc . Propose opening a separate PR to make the more substantial suggested improvements to the proxy guide so that the new quickstart is available. The separate PR will:
- use published images for services
- combine services in one docker compose

2023-07-07 13:03 UTC, merobi-hub commented on docs/guides/airflow_proxy.md
> +- Java 11
Java requirement removed. Propose making image change in separate PR.

2023-07-07 13:27 UTC, merobi-hub commented
Renamed `new-quickstart` as `airflow-quickstart`

2023-07-07 13:27 UTC, wslulciuc commented on docs/guides/airflow_proxy.md
> +This tutorial introduces you to using the [OpenLineage Proxy](https://github.com/OpenLineage/OpenLineage/tree/main/proxy) with Airflow. OpenLineage has various integrations that will enable Airflow t
You can also link to the sections in markdown ;)

2023-07-07 13:28 UTC, wslulciuc approved these changes
You officially have my blessing to us the Marquez example for Airflow! Great work! 💯

2023-07-07 13:31 UTC, merged