spark built-in lineage
OpenLineage/docs pull request #288
Opened 2024-02-26 11:53 UTC by pawel-big-lebowski

https://github.com/OpenLineage/OpenLineage/pull/2272

2024-02-26 11:54 UTC, pawel-big-lebowski commented
TODO: describe interface for DataSourceV2

2024-03-05 12:02 UTC, mobuchowski requested changes

2024-03-05 12:02 UTC, mobuchowski commented on docs/integrations/spark/built_in_lineage.md
> +sense to delegate dataset extraction to other node, while still having the ability to enrich it
I think it needs more context and explanation about this delegation process. It does not explain what happens when you use it - control goes back to OpenLineage integration and it uses the delegated LogicalPlan node to determine particular dataset. It also does not explain that you depend on that LogicalPlan node to have proper implementation whether using this mechanism or directly in OpenLineage.

2024-03-05 12:02 UTC, mobuchowski commented on docs/integrations/spark/built_in_lineage.md
> +            .foreach(expr => deps += ExpressionDependencyWithDelegate(OlExprId(attr.exprId.id), expr))
Again, there's no explanation of the delegate process.

2024-04-01 13:37 UTC, harels commented
@pawel-big-lebowski should we take this out of draft and review since we merged #2272?

2024-04-15 11:27 UTC, mobuchowski reviewed
I like the doc, but I think it's not relevant to the users of the Spark integration. 

Rather, it's useful for people developing spark extensions, so it would be better to put it in `docs/development/developing/spark`

2024-04-19 06:46 UTC, pawel-big-lebowski commented on docs/development/developing/spark/built_in_lineage.md
> +In the section above, the straightforward approach was used to identify dataset's `namespace` as `name`,
thanks @ddebowczyk92. I rephrased this,

2024-04-19 06:46 UTC, pawel-big-lebowski commented
> I like the doc, but I think it's not relevant to the users of the Spark integration.
> 
> Rather, it's useful for people developing spark extensions, so it would be better to put it in `docs/development/developing/spark`

Moved whole page to development section as suggested.

2024-04-19 08:32 UTC, mobuchowski approved these changes

2024-04-19 08:32 UTC, merged