Add compression option to HttpTtansport
OpenLineage/docs pull request #318
Opened 2024-04-15 09:26 UTC by dolfinus

Documentation for new `HttpTransport` config option `compression`, introduced in https://github.com/OpenLineage/OpenLineage/issues/2595

2024-04-15 10:18 UTC, kacpermuda approved these changes

2024-04-15 10:20 UTC, kacpermuda requested changes
Actually, could you please add somewhere in the description that this option is only available since version 1.13 ?

2024-04-16 12:40 UTC, pawel-big-lebowski approved these changes

2024-04-16 15:24 UTC, dolfinus commented
> Actually, could you please add somewhere in the description that this option is only available since version 1.13 ?

Ok, I'll push a commit later

2024-04-17 15:21 UTC, dolfinus commented
Added a note that this option was added since 1.13.0

2024-04-18 17:16 UTC, merged