airflow: add lineage in operator docs
OpenLineage/docs pull request #57
Opened 2022-10-19 15:15 UTC by mobuchowski

Add docs how to use feature from https://github.com/OpenLineage/OpenLineage/pull/1162 PR

Signed-off-by: Maciej Obuchowski <obuchowski.maciej@gmail.com>

2022-10-19 15:46 UTC, JDarDagran approved these changes

2022-10-19 16:28 UTC, merobi-hub requested changes
Thank you for this addition to the docs. May I suggest some edits (mainly adding missing articles)?
7: ^the OpenLineage Airflow
8: add external operators to the integration -- for example, ^a regular user who wants to support ^the ...
10: to add ^the
11: we have ^an
11: ^the `get_openlineage_facets`
14: from ^an operator

2022-11-04 03:48 UTC, howardyoo approved these changes

2022-11-04 14:31 UTC, merobi-hub approved these changes
LGTM!

2022-11-04 16:14 UTC, merged